---
- debug: var=hostvars['app-server-0'].ansible_host
  tags:
    - grafana
- debug: var=hostvars['grafana-server-0'].ansible_host
  tags:
    - influxdb
- name: Create conf dir
  file:
    path: /tmp/conf
    state: directory
  tags:
    - influxdb
- name: Create data_influxdb dir
  file:
    path: /tmp/data_influxdb
    state: directory
  tags:
    - influxdb
- name: Create data_chronograf dir
  file:
    path: /tmp/data_chronograf
    state: directory
  tags:
    - influxdb

- name: Add consul config
  template:
    src: "influxdb.conf.j2"
    dest: "/tmp/conf/influxdb.conf"
  tags:
    - influxdb

- name: Change permission on influxdb.conf file
  file:
    path: /tmp/conf/influxdb.conf
    state: file
    owner: root
    group: root
    mode: 0777

- name: Change permission on data_influxdb
  file:
    path: /tmp/data_influxdb
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Change permission on data_chronograf
  file:
    path: /tmp/data_chronograf
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Change permission on conf
  file:
    path: /tmp/conf
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Start a influxdb
  docker_container:
    name: influxdb
    image: influxdb:1.8
    state: started
    volumes:
      - /tmp/data_influxdb:/var/lib/influxdb
      - /tmp/conf/influxdb.conf:/etc/influxdb/influxdb.conf
    env:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_USERNAME: "admin"
      INFLUXDB_PASSWORD: "admin"
      INFLUXDB_DB: "gatlingdb"
    ports:
      - "8086:8086"
      - "2003:2003"
    restart: yes
  tags:
    - influxdb

- name: Start a chronograf
  docker_container:
    name: chronograf
    image: chronograf:latest
    state: started
    volumes:
      - /tmp/data_chronograf:/var/lib/chronograf
      - /tmp/conf/influxdb.conf:/etc/influxdb/influxdb.conf
    env:
      INFLUXDB_URL: "http://{{hostvars['grafana-server-0'].ansible_host}}:8086"
      INFLUXDB_USERNAME: "admin"
      INFLUXDB_PASSWORD: "admin"
    ports:
      - "{{hostvars['grafana-server-0'].ansible_host}}:8888:8888"
    restart: yes
  tags:
    - influxdb